version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: almino-dupeguru_server_1
      APP_PORT: 5800
    
  server:
    image: jlesage/dupeguru
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/server:/config
      - ${UMBREL_ROOT}/data/storage:/storage
